
//------------------------
// <auto-generated>
//     Generated with HiveMP SDK Generator
// </auto-generated>
//------------------------




#if UNITY_5 || UNITY_5_3_OR_NEWER
#define IS_UNITY
#endif
#if !(NET35 || (IS_UNITY && !NET_4_6))
#define HAS_TASKS
#endif
#if !NET35 && !IS_UNITY
#define HAS_HTTPCLIENT
#endif
#if IS_UNITY && NET_4_6 && UNITY_2017_1
#error Unity 2017.1 with a .NET 4.6 runtime is not supported due to known bugs in Unity (bit.ly/2xeicxY). Either upgrade to 2017.2 or use the .NET 2.0 runtime.
#endif


using System;
using System.IO;
using System.Threading;

namespace HiveMP.Api
{
    public class HiveMPException : Exception
    {
        static HiveMPException()
        {
            HiveMP.Api.HiveMPSDK.EnsureInited();
        }

        public HiveMPException(int httpStatusCode, HiveMPSystemError error)
            : base(GenerateMessageFromError(error))
        {
            HttpStatusCode = httpStatusCode;
            Error = error;
        }

        private static string GenerateMessageFromError(HiveMPSystemError error)
        {
            var errorCode = 0;
            var errorMessage = "";
            var errorFields = "";
            if (error != null)
            {
                errorCode = error.Code ?? 0;
                if (error.Message != null)
                {
                    errorMessage = error.Message;
                }
                if (error.Fields != null)
                {
                    errorFields = error.Fields;
                }
            }
            return "#" + errorCode + ": " + errorMessage + " (" + errorFields + ")";
        }

        public int HttpStatusCode { get; set; }

        public HiveMPSystemError Error { get; set; }
    }
}    
